<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category  Symmetrics
 * @package   Symmetrics_TweaksGerman
 * @author    symmetrics gmbh <info@symmetrics.de>
 * @author    Siegfried Schmitz <ss@symmetrics.de>
 * @copyright 2009-2010 symmetrics gmbh
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      http://www.symmetrics.de/
 */
?>

<script type="text/javascript">
//<![CDATA[
/**
 * Change the position from zip and city - fields.
 */
document.observe('dom:loaded', function() {
    if ($('city') && $('zip')) {
        var cityField = $('city').up().up();
        var zipField = $('zip').up().up().innerHTML;
        $('zip').up().up().update(cityField.innerHTML);
        $('city').up().up().update(zipField);
    }
    var regions = <?php echo Mage::helper('directory')->getRegionJson() ?>;
    new RegionUpdater('country', 'region', 'region_id', regions, undefined, 'zip');
});

new Symmetrics.Province();
//]]>
</script>
