<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category  Symmetrics
 * @package   Symmetrics_TweaksGerman
 * @author    symmetrics gmbh <info@symmetrics.de>
 * @author    Eugen Gitin <eg@symmetrics.de>
 * @copyright 2009-2010 symmetrics gmbh
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      http://www.symmetrics.de/
 */
?>

<?php $emailNotice = $this->helper('tweaksgerman')->getEmailNotice() ?>

<?php if (strlen(trim($emailNotice)) > 0): ?>
<script type="text/javascript"> 
//<![CDATA[
document.observe('dom:loaded', function() {
    var emailNotice = '<p class="email-notice"><?php echo $emailNotice ?></p>';
    $$('#opc-billing .validate-email', '.account-create .validate-email').each(function(item) {
        item.insert({ after: emailNotice });
    });
});
//]]>
</script>
<?php endif ?>