<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category  Symmetrics
 * @package   Symmetrics_TweaksGerman
 * @author    symmetrics gmbh <info@symmetrics.de>
 * @author    Eric Reiche <er@symmetrics.de>
 * @author    Ngoc Anh Doan <nd@symmetrics.de>
 * @copyright 2010-2011 symmetrics gmbh
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      http://www.symmetrics.de/
 */

/**
 * - frontend/default/default/template/tweaksgerman/weight.phtml
 */
?>
<?php $_weightLabel = $this->getAttributeLabel('weight') ?>
<?php $_weightLink = $this->getWeightLink() ?>

<script type="text/javascript">
//<![CDATA[
    document.observe('dom:loaded', function() {
        var labels = $$('#product-attribute-specs-table .label');
        labels.each(function(label) {
            if (label.innerHTML.match('<?php echo $_weightLabel ?>') !== null) {
                label.update('<a href="<?php echo $_weightLink ?>">' + label.innerHTML + '<\/a>');
            }
        });
    });
//]]>
</script>
