<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category  Symmetrics
 * @package   Symmetrics_SecurePassword
 * @author    symmetrics gmbh <info@symmetrics.de>
 * @author    Eric Reiche <er@symmetrics.de>
 * @copyright 2010 symmetrics gmbh
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      http://www.symmetrics.de/
 */
?>
<?php $notice = Mage::helper('securepassword')->__('For a secure password, use a password which is longer than 6 characters, which is not identical<br /> with the e-mail address and contains numbers or special characters.') ?>
<script type="text/javascript">
//<![CDATA[
document.observe('dom:loaded', function() {
    var passwordNotice = '<p class="passwordnotice"><?php echo $notice ?><\/p>';
    $('password').up().insert({after: passwordNotice });
});
//]]>
</script>